name: slidable_button
description: A simple customizable flutter slide button widget.
version: 1.3.1
homepage: https://github.com/husainazkas/slidable_button

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
