name: slidable_button
description: A simple customizable flutter slide button widget.
version: 2.0.0+1
homepage: https://github.com/husainazkas/slidable_button

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
