name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout to Slidable Button'
        uses: action/slidable_button@master
      - name: '>>Publishing package...<<'
        uses: k-paxian/dart-package-publisher@v1.6
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
